### ISSUE TITLE
[Questions]overall score for signal metric and script for downstream tasks

### ISSUE THREAD

**Issue by Slyne** [voidful/Codec-SUPERB#29]
Hi developers,

I find your paper is quite useful to evaluate the generated codec.
Here are two questions I have so far:
Do we have the overall score measurement script ? I find there's a `metrics.py` implementing all the required signal level metrics. And I've tested it and it works well. But I couldn't find how to combine the metrics together to get an overall score as mentioned in the paper.

And for the downstream tasks, do we have any plan to share the evaluation scripts?

Thanks!

**Comment by hbwu-ntu** [comment]
Please refer to Branch SLT_Challenge
