### ISSUE TITLE
How to run the evaluations on GPU?

### ISSUE THREAD

**Issue by JohnHerry** [voidful/Codec-SUPERB#43]
I want to use metrics in the project to make evaluations on my dataset. I write my testing script according to the benchmarking.py,  and all metrics runs well when on CPU defaultly,  but when I try to put generated audio and original audio onto cuda, it will run into error about the tqdm.contrib.multiprocessing.process_map will raise exceptions about: "Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the `spawn` start method".

**Comment by voidful** [comment]
Hi 
the benchmarking metrics is inside here: https://github.com/voidful/Codec-SUPERB/blob/main/metrics.py
basically it use cpu only to calculate the metrics, it is not supported GPU for now

**Comment by JohnHerry** [comment]
> Hi the benchmarking metrics is inside here: https://github.com/voidful/Codec-SUPERB/blob/main/metrics.py basically it use cpu only to calculate the metrics, it is not supported GPU for now

Thank you for the info.  feel sorry for loss support of GPU, because the CPU running is too slow now.
